apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    app: helloworld
  name: helloworld
  namespace: default
spec:
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - image: asia.gcr.io/techcon/helloworld
        name: helloworld
        ports:
          - containerPort: 80
